#pragma once

#include <string>
#include <vector>

namespace vars {

const double male_probability = 6;
const std::string alphanum =
    "qwertyuiopasdfghjklzxcvbnm,.!1234567890QWERTYUIOPLKJHGFDSAZXCVBNM";

const std::vector<double> account_creation_weights = {0.1, 0.15, 0.2, 0.25,
                                                      0.3};
// according to our survey data for user age groups: [18-30] = 66%, [30-45] =
// 23% [45+] = rest
const std::vector<double> year_weights = {0.02, 0.04, 0.04, 0.03, 0.06,
                                          0.06, 0.09, 0.22, 0.25, 0.19};

const std::vector<double> hour_weights = {
    0.05, 0.04, 0.02, 0.02, 0.01, 0.01, 0,    0.03, 0.03,
    0.04, 0.04, 0.06, 0.06, 0.07, 0.06, 0.04, 0.06, 0.03,
    0.04, 0.05, 0.06, 0.05, 0.04, 0.04, 0.05};
const std::vector<std::string> male_names = {
    "Milan",     "Dragan",       "Marko",    "Davor",    "Ivan",
    "Mirko",     "Ilija",        "Ibrahim",  "Zoran",    "Mustafa",
    "Hasan",     "Drago",        "Nikola",   "Mehmed",   "Pero",
    "Dusan",     "Muhamed",      "Slavko",   "Branko",   "Milorad",
    "Petar",     "Anto",         "Jozo",     "Slobodan", "Milenko",
    "Zeljko",    "Osman",        "Goran",    "Ivo",      "Husein",
    "Ismet",     "Zora",         "Miroslav", "Mile",     "Jovo",
    "Zdravko",   "Omer",         "Mirsad",   "Mujo",     "Sulejman",
    "Milos",     "Salih",        "Nedeljko", "Rajko",    "Mladen",
    "Ahmet",     "Jasmin",       "Tadija",   "Ante",     "Ramiz",
    "Ranko",     "Safet",        "Asim",     "Rasim",    "Muharem",
    "Mato",      "Vlado",        "Meho",     "Rade",     "Nenad",
    "Bozo",      "Ivica",        "Senad",    "Jovan",    "Sead",
    "Bosko",     "Stojan",       "Suad",     "Esad",     "Franjo",
    "Fadil",     "TihomirZarko", "Nermin",   "Adem",     "Jusuf",
    "Salko",     "Vinko",        "Radovan",  "Stanko",   "Ratko",
    "Luka",      "Nedjo",        "Niko",     "Mijo",     "Predrag",
    "Ibro",      "Stevo",        "Fikret",   "Marinko",  "Radomir",
    "Vladimir",  "Hajrudin",     "Tomislav", "Desanka",  "Josip",
    "Ramo",      "Boro",         "Gojko",    "Marijan",  "Edin",
    "Zijad",     "Kasim",        "Stjepan",  "Izet",     "Milovan",
    "Joka",      "Avdo",         "Enver",    "Simo",     "Dusko",
    "Borislav",  "Samir",        "Bogdan",   "Zivko",    "Enes",
    "Miodrag",   "Aleksandar",   "Dzevad",   "Ferid",    "Dragomir",
    "Branislav", "Miladin",      "Abdulah",  "Ljubomir", "Mate",
    "Stipo",     "Radenko",      "Saban",    "Risto",    "Nihad",
    "Dzemal",    "Huso",         "Nedzad",   "Veljko",   "Emir",
    "Hazim",     "Nermina",      "Djuro",    "Hasib",    "Andrija",
    "Mitar",     "Djordje",      "Semsa",    "Djordjo",  "Ostoja",
    "Darko",     "Radivoje",     "Milivoje", "Ekrem",    "Halil",
    "Brane",     "Suljo",        "Cvija",    "Sinisa",   "Tomo",
    "Mihajlo",   "Fahrudin",     "Lazar",    "Vaso",     "Fehim",
    "Dragoljub", "Bajro",        "Nebojsa",  "Kemal",    "Budimir",
    "Refik",     "Momir",        "Vahid",    "Radoslav", "Smail",
    "Momcilo",   "Danilo",       "Milutin",  "Fuad",     "Andjelko",
    "Vojislav",  "Halid",        "Hamid",    "Cedo",     "Becir",
    "Franjo",    "Sava",         "Nusret",   "Dejan",    "Slavisa",
    "Mico",      "Ahmed",        "Zlatko",   "Adnan",    "Mehmedalija",
    "Vojin",     "Novak",        "Stevan",   "Sefan",    "Hasija",
    "Redzo",     "Rifet",        "Smajo",    "Almir",    "Sretko",
    "Bozidar",   "Spasoje",      "Sadik",    "Zahid",    "Pavo",
    "Ljubisa",   "Matija",       "Obrad",    "Miro",     "Velimir",
    "Stipe",     "Dalibor"};
const std::vector<std::string> female_names = {
    "Fatima",    "Mara",     "Nada",       "Dragica",   "Milka",
    "Ljubica",   "Ana",      "Ruza",       "Mira",      "Danica",
    "Marija",    "Mirjana",  "Emina",      "Dusanka",   "Radojka",
    "Kata",      "Katarina", "Gordana",    "Milica",    "Milena",
    "Stana",     "Janja",    "Nevenka",    "Andja",     "Ljiljana",
    "Jovanka",   "Slavica",  "Radmila",    "Jela",      "Anica",
    "Zorka",     "Amir",     "Jelena",     "Elena",     "Vesna",
    "Savo",      "Biljana",  "Fata",       "Branka",    "Mirsada",
    "Iva",       "Dragana",  "Marica",     "Borka",     "Senija",
    "Ramiza",    "Stoja",    "Mejra",      "Razija",    "Bosiljka",
    "Ruzica",    "Cvijeta",  "Mileva",     "Hatidza",   "Petra",
    "Senada",    "Fadila",   "Vera",       "Snjezana",  "Safija",
    "Mina",      "Rada",     "Jasmina",    "Savka",     "Rosa",
    "Hanifa",    "Enisa",    "Slobodanka", "Stojanka",  "Mila",
    "Koviljka",  "Dzemila",  "Emilija",    "Anka",      "Suada",
    "Amira",     "Munira",   "Nura",       "Darinka",   "Aida",
    "Aisa",      "Sadeta",   "Sasa",       "Sanja",     "Rasema",
    "Esma",      "Slavka",   "Ljubo",      "Rabija",    "Sefika",
    "Zdravka",   "Ivka",     "Fikreta",    "Vinka",     "Ranka",
    "Ankica",    "Jadranka", "Smilja",     "Zineta",    "Gospava",
    "Sladjana",  "Ismeta",   "Hasiba",     "Jasminka",  "Ljuba",
    "Jelka",     "Alma",     "Vida",       "Zlata",     "Zeljka",
    "Rajka",     "Edina",    "Bozica",     "Zorica",    "Hava",
    "Hanka",     "Azra",     "Sabina",     "Ajka",      "Ivanka",
    "Jure",      "Ferida",   "Hajra",      "Draginja",  "Slavojka",
    "Hata",      "Zahida",   "Bojana",     "Milanka",   "Zejna",
    "Snezana",   "Ajsa",     "Izeta",      "Cvija",     "Olga",
    "Ljeposava", "Milojka",  "Habiba",     "Ivana",     "Dijana",
    "Behija",    "Mevlida",  "Andjelka",   "Vasilija",  "Dervisa",
    "Emira",     "Munevera", "Zehra",      "Amela",     "Rahima",
    "Safeta",    "Saliha",   "Ilinka",     "Danijela",  "Bozana",
    "Bosa",      "Desa",     "Refija",     "Svjetlana", "Spomenka",
    "Nezir",     "Ifeta",    "Milosava",   "Bahrija",   "Arif",
    "Zagorka",   "Lucija",   "Gospa",      "Sava",      "Selma",
    "Ajisa",     "Zumra",    "Vidosava",   "Emin",      "Brankica",
    "Asima",     "Grozda",   "Kadira",     "Mitra",     "Dervis",
    "Halida",    "Naza",     "Vukosava",   "Lejla",     "Ljubinka",
    "Jasna",     "Sadika",   "Milja",      "Sanela",    "Amra",
    "Hana",      "Dobrila",  "Zlatka",     "Sabiha",    "Rukija",
    "Zekija",    "Almasa",   "Sofija",     "Andja",     "Nedeljka",
    "Natasa",    "Tatjana",  "Nezira",     "Mika",      "Marina",
    "Milijana",  "Zdenka",   "Zuhra",      "Zuhdija",   "Aleksandra",
    "Adila"

};

const std::vector<std::string> cities = {"Banovici",
                                         "Banja Luka",
                                         "Berkovici",
                                         "Bihac",
                                         "Bijeljina",
                                         "Bileca",
                                         "Bosanska Krupa",
                                         "Bosanski Petrovac",
                                         "Bosansko Grahovo",
                                         "Bratunac",
                                         "Brcko",
                                         "Breza",
                                         "Brod",
                                         "Bugojno",
                                         "Busovaca",
                                         "Buzim",
                                         "Cazin",
                                         "Centar",
                                         "Cajnice",
                                         "Capljina",
                                         "Celic",
                                         "Celinac",
                                         "Citluk",
                                         "Derventa",
                                         "Doboj",
                                         "Doboj-Istok",
                                         "Doboj-Jug",
                                         "Dobretici",
                                         "Domaljevac-Samac",
                                         "Donji Vakuf",
                                         "Donji Zabar",
                                         "Drvar",
                                         "Foca (FBiH)",
                                         "Foca (RS)",
                                         "Fojnica",
                                         "Gacko",
                                         "Glamoc",
                                         "Gorazde",
                                         "Gornji Vakuf-Uskoplje",
                                         "Gracanica",
                                         "Gradacac",
                                         "Gradiska",
                                         "Grude",
                                         "Hadzici",
                                         "Han-Pijesak",
                                         "Ilidza",
                                         "Ilijas",
                                         "Istocna Ilidza",
                                         "Istocni Drvar",
                                         "Istocni Mostar",
                                         "Istocni Stari Grad",
                                         "Istocno Novo Sarajevo",
                                         "Istocno Sarajevo",
                                         "Jablanica",
                                         "Jajce",
                                         "Jezero",
                                         "Kakanj",
                                         "Kalesija",
                                         "Kalinovik",
                                         "Kiseljak",
                                         "Kladanj",
                                         "Kljuc",
                                         "Knezevo",
                                         "Konjic",
                                         "Kostajnica",
                                         "Kotor-Varos",
                                         "Kozarska Dubica",
                                         "Kresevo",
                                         "Krupa na Uni",
                                         "Kupres (FBiH)",
                                         "Kupres (RS)",
                                         "Laktasi",
                                         "Livno",
                                         "Lopare",
                                         "Lukavac",
                                         "Ljubinje",
                                         "Ljubuski",
                                         "Maglaj",
                                         "Milici",
                                         "Modrica",
                                         "Mostar",
                                         "Mrkonjic Grad",
                                         "Neum",
                                         "Nevesinje",
                                         "Novi Grad",
                                         "Novi Grad (Sarajevo)",
                                         "Novi Travnik",
                                         "Novo Gorazde",
                                         "Novo Sarajevo",
                                         "Odzak",
                                         "Olovo",
                                         "Orasje",
                                         "Osmaci",
                                         "Ostra Luka",
                                         "Pale (FBiH)",
                                         "Pale (RS)",
                                         "Pelagicevo",
                                         "Petrovac",
                                         "Petrovo",
                                         "Posusje",
                                         "Prijedor",
                                         "Prnjavor",
                                         "Prozor-Rama",
                                         "Ravno",
                                         "Ribnik",
                                         "Rogatica",
                                         "Rudo",
                                         "Sanski Most",
                                         "Sapna",
                                         "Sarajevo",
                                         "Sokolac",
                                         "Srbac",
                                         "Srebrenica",
                                         "Srebrenik",
                                         "Stanari",
                                         "Stari Grad",
                                         "Stolac",
                                         "Samac",
                                         "Sekovici",
                                         "Sipovo",
                                         "Siroki Brijeg",
                                         "Teocak",
                                         "Teslic",
                                         "Tesanj",
                                         "Tomislavgrad",
                                         "Travnik",
                                         "Trebinje",
                                         "Trnovo (FBiH)",
                                         "Trnovo (RS)",
                                         "Tuzla",
                                         "Ugljevik",
                                         "Usora",
                                         "Vares",
                                         "Velika Kladusa",
                                         "Visoko",
                                         "Visegrad",
                                         "Vitez",
                                         "Vlasenica",
                                         "Vogosca",
                                         "Vukosavlje",
                                         "Zavidovici",
                                         "Zenica",
                                         "Zvornik",
                                         "Zepce",
                                         "Zivinice"};

const std::vector<std::string> surnames = {
    "Hodzic",      "Kovačevic",  "Markovic",      "Petrovic",
    "Tomic",       "Delic",      "Hadzic",        "Savic",
    "Halilovic",   "Babic",      "Maric",         "Jovanovic",
    "Ilic",        "Basic",      "Vukovic",       "Lukic",
    "Popovic",     "Knezevic",   "Simic",         "Nikolic",
    "Pavlovic",    "djuric",     "Mitrovic",      "Jovic",
    "Avdic",       "Begic",      "Bozic",         "Todorovic",
    "Marjanovic",  "Brkic",      "Peric",         "Ramic",
    "Tadic",       "Alic",       "Imamovic",      "Lazic",
    "Karic",       "Dedic",      "Stojanovic",    "djukic",
    "Bosnjak",     "Stevanovic", "Selimovic",     "Smajic",
    "Spahic",      "Filipovic",  "Jankovic",      "Vidovic",
    "Blagojevic",  "Gajic",      "Mujkic",        "Radic",
    "Pejic",       "Ristic",     "Bajric",        "Dizdarevic",
    "Milosevic",   "Beganovic",  "Muratovic",     "Mujic",
    "Besic",       "Music",      "sehic",         "Maksimovic",
    "Mehic",       "Mesic",      "Ostojic",       "Omerovic",
    "Juric",       "Matic",      "Andric",        "Mijatovic",
    "Topic",       "Suljic",     "Smajlovic",     "sabic",
    "Lučic",       "Vasic",      "Jahic",         "Jukic",
    "Zahirovic",   "coric",      "Lazarevic",     "Trifkovic",
    "Mahmutovic",  "Galic",      "Ivanovic",      "Hasanovic",
    "Novakovic",   "Husic",      "Topalovic",     "Jasarevic",
    "Mihajlovic",  "Kadric",     "Mandic",        "Kovač",
    "Petkovic",    "Hasic",      "Softic",        "saric",
    "Gavric",      "djokic",     "Stupar",        "simic",
    "Huskic",      "Sinanovic",  "Boskovic",      "Martinovic",
    "Divčic",      "sabanovic",  "Čausevic",      "cosic",
    "Stankovic",   "Lovric",     "Jusic",         "zivkovic",
    "Osmanovic",   "Bogdanovic", "Stanic",        "Samardzic",
    "Masic",       "Damjanovic", "Čolic",         "Grgic",
    "Mujkanovic",  "Subasic",    "Memic",         "Fazlic",
    "Muminovic",   "Micic",      "Hamzic",        "Salkic",
    "Milanovic",   "Jokic",      "Begovic",       "Zukic",
    "Milic",       "Salihovic",  "Pasic",         "Terzic",
    "Janjic",      "Panic",      "Mehmedovic",    "Radovanovic",
    "Bojic",       "Ahmetovic",  "Spasojevic",    "Pajic",
    "Stjepanovic", "Tesic",      "Mikulic",       "Bilic",
    "sisic",       "Durakovic",  "Jovičic",       "Vasiljevic",
    "Vidakovic",   "Dzafic",     "Ibrahimovic",   "Nisic",
    "Zovko",       "Nedic",      "Bajic",         "Misic",
    "Aleksic",     "Pandurevic", "Kadic",         "Mujanovic",
    "Mestrovac",   "Bajramovic", "Stevic",        "Redzic",
    "Kurtovic",    "Makic",      "Music",         "Nesust",
    "Sarajlic",    "Blazevic",   "Milovanovic",   "Jelic",
    "Mustafic",    "Kojic",      "Stanisic",      "Rakic",
    "Pasalic",     "Pantic",     "Fejzic",        "Marinkovic",
    "Muharemovic", "Obradovic",  "Ivankovic",     "Josipovic",
    "Miletic",     "Nikic",      "Krstic",        "Medic",
    "Velic",       "Saric",      "Imsirovic",     "Dragic",
    "Arnautovic",  "Lakic",      "Pavic",         "catic",
    "Becirovic",   "Cvijanovic", "Zec",           "Miličevic",
    "Mujagic",     "Talic",      "Mirkovic",      "Tabakovic",
    "Zečevic",     "Grbic",      "Mesanovic",     "Omanovic",
    "Milinkovic",  "Miskovic",   "Rajic",         "Majstorovic",
    "Radovic",     "Buljubasic", "Soldo",         "Zekic",
    "Starčevic",   "Milicevic",  "Kapetanovic",   "Tesanovic",
    "Joldic",      "Vučic",      "Subotic",       "Agic",
    "Zaric",       "Stanojevic", "Davidovic",     "Kuzmanovic",
    "Vujic",       "Mijic",      "Sadikovic",     "curic",
    "Ahmic",       "Zoric",      "Demirovic",     "Divkovic",
    "Nuhanovic",   "Kostic",     "Lalovic",       "Eric",
    "Alagic",      "Hajdarevic", "Mikic",         "Močevic",
    "Dragicevic",  "Barisic",    "Perkovic",      "Okanovic",
    "Lončar",      "Ninkovic",   "Isakovic",      "Martic",
    "Jurisic",     "Leko",       "Bajraktarevic", "Duric",
    "Jakovljevic", "Čajic",      "Bratic",        "Pilipovic",
    "Dzinic",      "Sekulic",    "Josic",         "Kljajic",
    "Omeragic",    "Dervisevic", "Okic",          "Malic",
    "Rados",       "Kresic",     "Garic",         "Vidic",
    "Duvnjak",     "Vlačic",     "Pandzic",       "Banovic",
    "Grujic",      "Čovic",      "Radulovic",     "Cvjetkovic",
    "djurdjevic",  "Ikanovic",   "Malesevic",     "Stojic",
    "Kapic",       "Antic",      "Pranjic",       "Tokic",
    "Prodanovic",  "Rizvic",     "Radan",         "Kraljevic",
    "Ljubijankic", "Ivkovic",    "Primorac",      "Antunovic",
    "Krsmanovic",  "Budimir",    "Jozic",         "Muhic",
    "Jevtic",      "Skopljak",   "Koprivica",     "Mujezinovic",
    "sahinovic",   "Bijelic",    "Dukic",         "Todic",
    "Hasanbasic",  "Neskovic",   "Kukic",         "Vasilj",
    "Zulic",       "Samardzija", "Balic",         "Kahric",
    "Pehar",       "Batinic",    "Dautovic",      "Karalic",
    "Rahmanovic",  "Hrnjic",     "Čolakovic",     "djukanovic",
    "Marijanovic", "sarac",      "Nukic",         "Simeunovic",
    "Banjac",      "Ribic",      "Grujičic",      "Jusufovic",
    "Osmic",       "Susic",      "Jerkovic",      "Knezovic",
    "Čamdzic",     "Vujinovic",  "Kulic",         "Bojanic",
    "strbac",      "Kurtic",     "cehic",         "Kopic",
    "Vučkovic",    "Jovančic",   "Dujmovic",      "Alihodzic",
    "Bukvic",      "Aljic",      "Islamovic",     "Gojkovic",
    "Grabovac",    "Golubovic",  "Smiljanic",     "Vrhovac",
    "Matijevic",   "Ivic",       "Jokanovic",     "Vujičic",
    "Mahmic",      "Cvijetic",   "Gavranovic",    "Katic",
    "Kristo",      "Crnogorac",  "sarčevic",      "sehovic",
    "Kulina",      "Ibric",      "Tosic",         "Jeremic",
    "Krajisnik",   "Golic",      "Vilic",         "Vranjes",
    "Bjelica",     "Tahirovic",  "Dakic",         "Hamidovic",
    "Salkanovic",  "Dabic",      "Grbavac",       "Mrkonjic",
    "Stojakovic",  "Alispahic",  "Sliskovic",     "zilic",
    "Adamovic",    "Mulalic",    "Kordic",        "Arapovic",
    "Marinovic",   "Huseinovic", "Manojlovic",    "Cvjetinovic",
    "Kasumovic",   "Zeko",       "Bečic",         "Simikic",
    "Alibasic",    "Miljanovic", "Vukoja",        "Junuzovic",
    "Kalajdzic",   "djakovic",   "Gavrilovic",    "djekic",
    "Glisic",      "Petrusic",   "Milos",         "djordjic",
    "Nuhic",       "Beslic",     "Majkic",        "Plavsic",
    "Musa",        "zivanovic",  "Perisic",       "skrba",
    "Acimovic",    "Dzebo",      "Kondic",        "Čelikovic",
    "Karačic",     "Tubic",      "Durmic",        "Golijanin",
    "Tursunovic",  "Bagaric",    "Zrnic",         "Draskovic",
    "Alibegovic",  "Despotovic", "Elez",          "Čuljak",
    "Macanovic",   "Rosic",      "Vasilic",       "Musanovic",
    "Pjanic",      "Hukic",      "Kahrimanovic",  "simunovic",
    "Ratkovic",    "Omic",       "Mehanovic",     "Vaskovic",
    "Bevanda",     "Cvijic",     "Aganovic",      "Tepic"};
} // namespace vars